In [9]:
import pandas as pd
from pandas import Series, DataFrame

# Beyond 1

Ignore the `password` and `groupid` fields, such that they don't appear in the data frame.


번역: password와 groupid 필드를 무시하여 데이터프레임에 나타나지 않도록 하세요.

In [10]:
# Note that we name all columns, and then only use a subset of them
df = pd.read_csv('../data/linux-etc-passwd.txt', 
                 sep=':', comment='#', header=None,
                 usecols=['username', 'userid', 'name', 'homedir', 'shell'],
                names=['username', 'password', 'userid', 'groupid', 'name', 'homedir', 'shell'])
df
#names로 컬럼명을 지정해주고, usecols로 필요한 컬럼만 골라서 사용

,username,userid,name,homedir,shell
0,root,0,root,/root,/bin/bash
1,daemon,1,daemon,/usr/sbin,/usr/sbin/nologin
2,bin,2,bin,/bin,/usr/sbin/nologin
3,sys,3,sys,/dev,/usr/sbin/nologin
4,sync,4,sync,/bin,/bin/sync
5,games,5,games,/usr/games,/usr/sbin/nologin
6,man,6,man,/var/cache/man,/usr/sbin/nologin
7,lp,7,lp,/var/spool/lpd,/usr/sbin/nologin
8,mail,8,mail,/var/mail,/usr/sbin/nologin
9,news,9,news,/var/spool/news,/usr/sbin/nologin
10,uucp,10,uucp,/var/spool/uucp,/usr/sbin/nologin
11,proxy,13,proxy,/bin,/usr/sbin/nologin
12,www-data,33,www-data,/var/www,/usr/sbin/nologin
13,backup,34,backup,/var/backups,/usr/sbin/nologin
14,list,38,Mailing List Manager,/var/list,/usr/sbin/nologin
15,irc,39,ircd,/var/run/ircd,/usr/sbin/nologin
16,gnats,41,Gnats Bug-Reporting System (admin),/var/lib/gnats,/usr/sbin/nologin
17,nobody,65534,nobody,/nonexistent,/usr/sbin/nologin
18,syslog,101,NaN,/home/syslog,/bin/false
19,messagebus,102,NaN,/var/run/dbus,/bin/false
20,landscape,103,NaN,/var/lib/landscape,/bin/false
21,jci,955,NaN,/home/jci,/bin/bash
22,sshd,104,NaN,/var/run/sshd,/usr/sbin/nologin
23,user,1000,"user,,,",/home/user,/bin/bash
24,reuven,1001,"Reuven M. Lerner,,,",/home/reuven,/bin/bash
25,postfix,105,NaN,/var/spool/postfix,/bin/false
26,colord,106,"colord colour management daemon,,,",/var/lib/colord,/bin/false
27,postgres,107,"PostgreSQL administrator,,,",/var/lib/postgresql,/bin/bash
28,dovecot,108,"Dovecot mail server,,,",/usr/lib/dovecot,/bin/false
29,dovenull,109,"Dovecot login user,,,",/nonexistent,/bin/false
30,postgrey,110,NaN,/var/lib/postgrey,/bin/false
31,debian-spamd,111,NaN,/var/lib/spamassassin,/bin/sh
32,memcache,113,"Memcached,,,",/nonexistent,/bin/false
33,genadi,1002,"Genadi Reznichenko,,,",/home/genadi,/bin/bash
34,shira,1003,"Shira Friedman,,,",/home/shira,/bin/bash
35,atara,1004,"Atara Lerner-Friedman,,,",/home/atara,/bin/bash
36,shikma,1005,"Shikma Lerner-Friedman,,,",/home/shikma,/bin/bash
37,amotz,1006,"Amotz Lerner-Friedman,,,",/home/amotz,/bin/bash
38,mysql,114,"MySQL Server,,,",/nonexistent,/bin/false
39,clamav,115,NaN,/var/lib/clamav,/bin/false
40,amavis,116,"AMaViS system user,,,",/var/lib/amavis,/bin/sh
41,opendkim,117,NaN,/var/run/opendkim,/bin/false
42,gitlab-redis,999,NaN,/var/opt/gitlab/redis,/bin/nologin
43,gitlab-psql,998,NaN,/var/opt/gitlab/postgresql,/bin/sh
44,git,1007,"GitLab,,,",/home/git,/bin/bash
45,opendmarc,118,NaN,/var/run/opendmarc,/bin/false
46,dkim-milter-python,119,NaN,/var/run/dkim-milter-python,/bin/false
47,deploy,1008,"Deploy,,,",/home/deploy,/bin/bash
48,redis,112,"redis server,,,",/var/lib/redis,/bin/false

# Beyond 2

Unix systems typically reserve user IDs below 1000 to special accounts.  Show the non-special usernames in this `passwd` file.

번역: 유닉스 시스템에서는 일반적으로 사용자 ID 1000 미만을 특수 계정에 할당합니다. 이 passwd 파일에서 특수 계정이 아닌 사용자 이름들을 보여주세요.

In [11]:
df = pd.read_csv('../data/linux-etc-passwd.txt',
                 sep=':', comment='#', header=None,
                names=['username', 'password', 'userid', 'groupid', 'name', 'homedir', 'shell'])

df[df['userid'] > 1000]
# >= 이 아닌, >가 맞음.


# 대부분의 현대 리눅스 배포판(예: Debian/Ubuntu, 최신 Fedora 등)에서는 UID 1000부터 일반(사람) 사용자 계정을 할당합니다.

# 0: root
# 1–99: 전통적 시스템 계정
# 100–999: 서비스/시스템 계정
# 1000 이상: 일반 사용자
# 예외: 오래된 Red Hat 계열은 500부터 시작했고, 일부 시스템은 정책을 바꿀 수 있습니다. 따라서 “보통 1000은 일반 사용자”가 맞지만, 절대적인 규칙은 아니며 /etc/login.defs 의 UID_MIN 값을 확인하면 확실합니다.

,username,password,userid,groupid,name,homedir,shell
17,nobody,x,65534,65534,nobody,/nonexistent,/usr/sbin/nologin
24,reuven,x,1001,1001,"Reuven M. Lerner,,,",/home/reuven,/bin/bash
33,genadi,x,1002,1003,"Genadi Reznichenko,,,",/home/genadi,/bin/bash
34,shira,x,1003,1004,"Shira Friedman,,,",/home/shira,/bin/bash
35,atara,x,1004,1005,"Atara Lerner-Friedman,,,",/home/atara,/bin/bash
36,shikma,x,1005,1006,"Shikma Lerner-Friedman,,,",/home/shikma,/bin/bash
37,amotz,x,1006,1007,"Amotz Lerner-Friedman,,,",/home/amotz,/bin/bash
44,git,x,1007,1008,"GitLab,,,",/home/git,/bin/bash
47,deploy,x,1008,1011,"Deploy,,,",/home/deploy,/bin/bash

# Beyond 3

Immediately after logging into a Unix system, a command interpreter, known as a "shell," fires up. What are the different shells in this file?


번역: 유닉스 시스템에 로그인하자마자 “셸(shell)”이라 불리는 명령 해석기가 실행됩니다. 이 파일에 나타나는 서로 다른 셸은 무엇인가요?

In [12]:
# The `unique` method does this for us, returning a NumPy array -- but Pandas offers its own
# drop_duplicates method, which keeps us with a series
# 번역: unique 메서드는 이를 수행하여 NumPy 배열을 반환합니다. 
# 그러나 Pandas는 자체 drop_duplicates 메서드를 제공하며, 이를 사용하면 Series 형태를 유지할 수 있습니다.

df['shell'].drop_duplicates()

#drop_duplicates() : 중복된 값을 제거하고 고유한 값만 남깁니다.
#넘파이 에서는 unique() 메서드를 사용하며, 넘파이 어레이를 반환한다.

0             /bin/bash
1     /usr/sbin/nologin
4             /bin/sync
18           /bin/false
31              /bin/sh
42         /bin/nologin
Name: shell, dtype: object